name: CI Build for PR
run-name: Building code for ${{ github.actor }} ğŸš€
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  CI-Build:
    runs-on: ubuntu-latest
    steps:
      - name: some information
        run: |
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: checkout code with submodules
        uses: actions/checkout@v5
        with: 
          submodules: recursive

      - name: build release version
        # if: github.event.name == 'pull_request'
        run: |
          cmake -S. -Bbuild
          cmake --build build --config Release --target heliconia --verbose